# Generated by Django 5.0.2 on 2024-08-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(blank=True, help_text='생년월일 (YYYYMMDD)', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.PositiveSmallIntegerField(blank=True, help_text='0: 남자, 1: 여자, 2: 알수없음', null=True),
        ),
    ]
